# Generated by Django 5.2.4 on 2025-08-02 11:29

import apps.collections.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Название коллекции (максимум 200 символов)', max_length=200, verbose_name='Название коллекции')),
                ('slug', models.SlugField(help_text='Уникальный URL-адрес коллекции', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Подробное описание коллекции', verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, help_text='Краткое описание для превью (максимум 500 символов)', max_length=500, verbose_name='Краткое описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли коллекцию на сайте', verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Порядок отображения коллекций (меньше = выше)', verbose_name='Порядок сортировки')),
                ('featured', models.BooleanField(default=False, help_text='Отмечать ли коллекцию как рекомендуемую', verbose_name='Рекомендуемая')),
                ('meta_title', models.CharField(blank=True, help_text='SEO заголовок (максимум 60 символов)', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='SEO описание (максимум 160 символов)', max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='collections_is_acti_ae4cb6_idx'), models.Index(fields=['featured', 'is_active'], name='collections_feature_6ce76f_idx'), models.Index(fields=['slug'], name='collections_slug_60b735_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Изображение коллекции (форматы: JPG, PNG, WebP)', upload_to=apps.collections.models.collection_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, help_text='Альтернативный URL изображения (если не загружено локально)', null=True, verbose_name='URL изображения')),
                ('alt_text', models.CharField(blank=True, help_text='Альтернативный текст для изображения (для SEO и доступности)', max_length=200, verbose_name='Alt текст')),
                ('caption', models.CharField(blank=True, help_text='Подпись к изображению', max_length=500, verbose_name='Подпись')),
                ('is_primary', models.BooleanField(default=False, help_text='Использовать как основное изображение коллекции', verbose_name='Основное изображение')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли изображение', verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Порядок отображения изображений', verbose_name='Порядок сортировки')),
                ('width', models.PositiveIntegerField(blank=True, help_text='Ширина изображения в пикселях', null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, help_text='Высота изображения в пикселях', null=True, verbose_name='Высота')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Размер файла в байтах', null=True, verbose_name='Размер файла')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='collections.collection', verbose_name='Коллекция')),
            ],
            options={
                'verbose_name': 'Изображение коллекции',
                'verbose_name_plural': 'Изображения коллекций',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['collection', 'is_active', 'sort_order'], name='collections_collect_5488df_idx'), models.Index(fields=['collection', 'is_primary'], name='collections_collect_d96025_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('collection',), name='unique_primary_image_per_collection')],
            },
        ),
    ]
