# Generated by Django 5.2.4 on 2025-08-15 10:04

from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('image', 'Изображение'), ('slideshow', 'Слайдшоу'), ('video', 'Видео')], max_length=20, verbose_name='Тип контента')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фоновый контент',
                'verbose_name_plural': 'Фоновый контент',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/', verbose_name='Изображение')),
                ('width', models.PositiveIntegerField(default=1920, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(default=1080, verbose_name='Высота')),
                ('scaling_mode', models.CharField(choices=[('cover', 'Покрыть (cover)'), ('contain', 'Вместить (contain)'), ('fill', 'Заполнить (fill)')], default='cover', max_length=20, verbose_name='Режим масштабирования')),
                ('background_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_image', to='background_content.backgroundcontent', verbose_name='Фоновый контент')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновые изображения',
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.PositiveIntegerField(default=5000, help_text='Интервал между слайдами в миллисекундах', verbose_name='Интервал смены (мс)')),
                ('transition_duration', models.PositiveIntegerField(default=1000, help_text='Длительность анимации перехода в миллисекундах', verbose_name='Длительность перехода (мс)')),
                ('background_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slideshow', to='background_content.backgroundcontent', verbose_name='Фоновый контент')),
            ],
            options={
                'verbose_name': 'Слайдшоу',
                'verbose_name_plural': 'Слайдшоу',
            },
        ),
        migrations.CreateModel(
            name='SlideshowImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('slideshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='background_content.slideshow', verbose_name='Слайдшоу')),
            ],
            options={
                'verbose_name': 'Изображение слайдшоу',
                'verbose_name_plural': 'Изображения слайдшоу',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(help_text='Ссылка на YouTube или Vimeo видео', max_length=500, verbose_name='URL видео')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo')], default='youtube', max_length=20, verbose_name='Платформа')),
                ('autoplay', models.BooleanField(default=True, verbose_name='Автовоспроизведение')),
                ('muted', models.BooleanField(default=True, verbose_name='Без звука')),
                ('loop', models.BooleanField(default=True, verbose_name='Зацикливание')),
                ('background_content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='background_video', to='background_content.backgroundcontent', verbose_name='Фоновый контент')),
            ],
            options={
                'verbose_name': 'Фоновое видео',
                'verbose_name_plural': 'Фоновые видео',
            },
        ),
    ]
