# Generated by Django 5.2.4 on 2025-08-16 10:52

import apps.background_content.models
import apps.background_content.validators.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_content', '0004_add_width_height_to_slideshowimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundvideo',
            name='playlist_mode',
            field=models.BooleanField(default=False, verbose_name='Режим плейлиста'),
        ),
        migrations.AddField(
            model_name='backgroundvideo',
            name='playlist_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в плейлисте'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px.', upload_to=apps.background_content.models.background_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Использовать это изображение как основное для фона сайта', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px. Рекомендуемое соотношение сторон: 16:9.', upload_to=apps.background_content.models.slideshow_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_slideshow_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
    ]
