# Generated by Django 5.2.4 on 2025-09-03 15:54

import apps.background_content.models
import apps.background_content.validators.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_content', '0006_alter_backgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px.', upload_to=apps.background_content.models.background_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px. Рекомендуемое соотношение сторон: 16:9.', upload_to=apps.background_content.models.slideshow_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_slideshow_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
    ]
