# Generated by Django 5.2.8 on 2025-12-10 15:29

import apps.background_content.models
import apps.background_content.validators.image_validator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_content', '0009_backgroundvideo_file_alter_backgroundimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundvideo',
            options={'verbose_name': 'Настройки видео', 'verbose_name_plural': 'Настройки видео'},
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px.', upload_to=apps.background_content.models.background_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slideshowimage',
            name='image',
            field=models.ImageField(help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP. Максимальный размер: 15MB. Минимальный размер: 400x300px. Рекомендуемое соотношение сторон: 16:9.', upload_to=apps.background_content.models.slideshow_image_upload_path, validators=[apps.background_content.validators.image_validator.BackgroundImageValidator.validate_slideshow_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='BackgroundVideoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('file', 'Локальный файл')], default='youtube', max_length=20, verbose_name='Платформа')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube или Vimeo видео', max_length=500, null=True, verbose_name='URL видео')),
                ('file', models.FileField(blank=True, help_text='Локальный видео файл (mp4, webm)', null=True, upload_to=apps.background_content.models.background_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'], message='Поддерживаемые форматы: MP4, WebM')], verbose_name='Видео файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('background_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_items', to='background_content.backgroundcontent', verbose_name='Фоновый контент')),
            ],
            options={
                'verbose_name': 'Видео элемент',
                'verbose_name_plural': 'Видео элементы',
                'ordering': ['order'],
            },
        ),
    ]
