from django.conf import settings

# Настройки системы безопасности

# Основные настройки
SECURITY_ENABLED = getattr(settings, 'SECURITY_ENABLED', True)
SECURITY_DEBUG = getattr(settings, 'SECURITY_DEBUG', False)

# Настройки middleware
SECURITY_MIDDLEWARE_ENABLED = getattr(settings, 'SECURITY_MIDDLEWARE_ENABLED', True)
SECURITY_BLOCK_REQUESTS = getattr(settings, 'SECURITY_BLOCK_REQUESTS', True)
SECURITY_CACHE_TIMEOUT = getattr(settings, 'SECURITY_CACHE_TIMEOUT', 300)

# Пути для проверки безопасности
SECURITY_PROTECTED_PATHS = getattr(settings, 'SECURITY_PROTECTED_PATHS', [
    '/api/auth/',
    '/api/registration/',
    '/api/verification/',
    '/api/user/',
    '/api/qr/',
    '/api/telegram/'
])

# Исключенные пути
SECURITY_EXCLUDED_PATHS = getattr(settings, 'SECURITY_EXCLUDED_PATHS', [
    '/admin/',
    '/static/',
    '/media/',
    '/api/security/',
    '/api/health/',
    '/favicon.ico'
])

# Rate limiting
SECURITY_MAX_REQUESTS_PER_MINUTE = getattr(settings, 'SECURITY_MAX_REQUESTS_PER_MINUTE', 60)
SECURITY_MAX_REQUESTS_PER_HOUR = getattr(settings, 'SECURITY_MAX_REQUESTS_PER_HOUR', 1000)
SECURITY_MAX_REQUESTS_PER_DAY = getattr(settings, 'SECURITY_MAX_REQUESTS_PER_DAY', 10000)

# Настройки отчетов безопасности
SECURITY_REPORT_MIDDLEWARE_ENABLED = getattr(settings, 'SECURITY_REPORT_MIDDLEWARE_ENABLED', True)
SECURITY_AUTO_BLOCK_ENABLED = getattr(settings, 'SECURITY_AUTO_BLOCK_ENABLED', False)
SECURITY_AUTO_BLOCK_THRESHOLD = getattr(settings, 'SECURITY_AUTO_BLOCK_THRESHOLD', 0.9)

# Настройки логирования
SECURITY_LOGGING_ENABLED = getattr(settings, 'SECURITY_LOGGING_ENABLED', True)
SECURITY_LOG_LEVEL = getattr(settings, 'SECURITY_LOG_LEVEL', 'WARNING')

# Настройки анализа устройств
DEVICE_FINGERPRINT_ENABLED = getattr(settings, 'DEVICE_FINGERPRINT_ENABLED', True)
DEVICE_FINGERPRINT_MIN_CONFIDENCE = getattr(settings, 'DEVICE_FINGERPRINT_MIN_CONFIDENCE', 0.5)
DEVICE_FINGERPRINT_CACHE_TIMEOUT = getattr(settings, 'DEVICE_FINGERPRINT_CACHE_TIMEOUT', 3600)

# Настройки поведенческого анализа
BEHAVIORAL_ANALYSIS_ENABLED = getattr(settings, 'BEHAVIORAL_ANALYSIS_ENABLED', True)
BEHAVIORAL_ANALYSIS_MIN_EVENTS = getattr(settings, 'BEHAVIORAL_ANALYSIS_MIN_EVENTS', 10)
BEHAVIORAL_ANALYSIS_TIMEOUT = getattr(settings, 'BEHAVIORAL_ANALYSIS_TIMEOUT', 300)

# Пороги риска
RISK_THRESHOLD_LOW = getattr(settings, 'RISK_THRESHOLD_LOW', 0.3)
RISK_THRESHOLD_MEDIUM = getattr(settings, 'RISK_THRESHOLD_MEDIUM', 0.6)
RISK_THRESHOLD_HIGH = getattr(settings, 'RISK_THRESHOLD_HIGH', 0.8)
RISK_THRESHOLD_CRITICAL = getattr(settings, 'RISK_THRESHOLD_CRITICAL', 0.9)

# Настройки обнаружения автоматизации
AUTOMATION_DETECTION_ENABLED = getattr(settings, 'AUTOMATION_DETECTION_ENABLED', True)
AUTOMATION_DETECTION_STRICT = getattr(settings, 'AUTOMATION_DETECTION_STRICT', False)

# Подозрительные User Agents
SUSPICIOUS_USER_AGENTS = getattr(settings, 'SUSPICIOUS_USER_AGENTS', [
    'bot', 'crawler', 'spider', 'scraper', 'curl', 'wget',
    'python-requests', 'selenium', 'phantomjs', 'headless',
    'automation', 'webdriver', 'chrome-headless'
])

# Автоматические User Agents
AUTOMATION_USER_AGENTS = getattr(settings, 'AUTOMATION_USER_AGENTS', [
    'selenium', 'webdriver', 'phantomjs', 'headlesschrome',
    'chromedriver', 'geckodriver', 'automation'
])

# Настройки черного списка
BLACKLIST_ENABLED = getattr(settings, 'BLACKLIST_ENABLED', True)
BLACKLIST_AUTO_EXPIRE = getattr(settings, 'BLACKLIST_AUTO_EXPIRE', True)
BLACKLIST_DEFAULT_DURATION_HOURS = getattr(settings, 'BLACKLIST_DEFAULT_DURATION_HOURS', 24)

# Настройки мониторинга угроз
THREAT_MONITORING_ENABLED = getattr(settings, 'THREAT_MONITORING_ENABLED', True)
THREAT_DETECTION_THRESHOLD = getattr(settings, 'THREAT_DETECTION_THRESHOLD', 0.7)
THREAT_AUTO_INVESTIGATION = getattr(settings, 'THREAT_AUTO_INVESTIGATION', False)

# Настройки уведомлений
SECURITY_NOTIFICATIONS_ENABLED = getattr(settings, 'SECURITY_NOTIFICATIONS_ENABLED', True)
SECURITY_EMAIL_NOTIFICATIONS = getattr(settings, 'SECURITY_EMAIL_NOTIFICATIONS', [])
SECURITY_WEBHOOK_URL = getattr(settings, 'SECURITY_WEBHOOK_URL', None)

# Настройки производительности
SECURITY_ASYNC_PROCESSING = getattr(settings, 'SECURITY_ASYNC_PROCESSING', True)
SECURITY_BATCH_SIZE = getattr(settings, 'SECURITY_BATCH_SIZE', 100)
SECURITY_CACHE_BACKEND = getattr(settings, 'SECURITY_CACHE_BACKEND', 'default')

# Настройки очистки данных
SECURITY_DATA_RETENTION_DAYS = getattr(settings, 'SECURITY_DATA_RETENTION_DAYS', 90)
SECURITY_AUTO_CLEANUP_ENABLED = getattr(settings, 'SECURITY_AUTO_CLEANUP_ENABLED', True)
SECURITY_CLEANUP_BATCH_SIZE = getattr(settings, 'SECURITY_CLEANUP_BATCH_SIZE', 1000)

# Настройки API
SECURITY_API_RATE_LIMIT = getattr(settings, 'SECURITY_API_RATE_LIMIT', '100/hour')
SECURITY_API_AUTHENTICATION_REQUIRED = getattr(settings, 'SECURITY_API_AUTHENTICATION_REQUIRED', True)
SECURITY_API_ADMIN_ONLY = getattr(settings, 'SECURITY_API_ADMIN_ONLY', True)

# Настройки интеграции с фронтендом
SECURITY_FRONTEND_ENABLED = getattr(settings, 'SECURITY_FRONTEND_ENABLED', True)
SECURITY_FRONTEND_TIMEOUT = getattr(settings, 'SECURITY_FRONTEND_TIMEOUT', 5000)
SECURITY_FRONTEND_RETRY_ATTEMPTS = getattr(settings, 'SECURITY_FRONTEND_RETRY_ATTEMPTS', 3)

# Настройки Canvas fingerprinting
CANVAS_FINGERPRINT_ENABLED = getattr(settings, 'CANVAS_FINGERPRINT_ENABLED', True)
CANVAS_FINGERPRINT_TEXT = getattr(settings, 'CANVAS_FINGERPRINT_TEXT', 'Security Check 🔒')

# Настройки WebGL fingerprinting
WEBGL_FINGERPRINT_ENABLED = getattr(settings, 'WEBGL_FINGERPRINT_ENABLED', True)

# Настройки аудио fingerprinting
AUDIO_FINGERPRINT_ENABLED = getattr(settings, 'AUDIO_FINGERPRINT_ENABLED', False)

# Настройки отслеживания мыши
MOUSE_TRACKING_ENABLED = getattr(settings, 'MOUSE_TRACKING_ENABLED', True)
MOUSE_TRACKING_SAMPLE_RATE = getattr(settings, 'MOUSE_TRACKING_SAMPLE_RATE', 100)  # мс
MOUSE_TRACKING_MAX_EVENTS = getattr(settings, 'MOUSE_TRACKING_MAX_EVENTS', 1000)

# Настройки отслеживания клавиатуры
KEYSTROKE_TRACKING_ENABLED = getattr(settings, 'KEYSTROKE_TRACKING_ENABLED', True)
KEYSTROKE_TRACKING_MAX_EVENTS = getattr(settings, 'KEYSTROKE_TRACKING_MAX_EVENTS', 500)

# Настройки отслеживания скролла
SCROLL_TRACKING_ENABLED = getattr(settings, 'SCROLL_TRACKING_ENABLED', True)
SCROLL_TRACKING_THROTTLE = getattr(settings, 'SCROLL_TRACKING_THROTTLE', 100)  # мс

# Настройки отслеживания фокуса
FOCUS_TRACKING_ENABLED = getattr(settings, 'FOCUS_TRACKING_ENABLED', True)

# Настройки анализа времени
TIMING_ANALYSIS_ENABLED = getattr(settings, 'TIMING_ANALYSIS_ENABLED', True)
MIN_FORM_FILL_TIME = getattr(settings, 'MIN_FORM_FILL_TIME', 2000)  # мс
MAX_FORM_FILL_TIME = getattr(settings, 'MAX_FORM_FILL_TIME', 300000)  # мс

# Настройки honeypot полей
HONEYPOT_ENABLED = getattr(settings, 'HONEYPOT_ENABLED', True)
HONEYPOT_FIELD_NAMES = getattr(settings, 'HONEYPOT_FIELD_NAMES', [
    'website', 'url', 'homepage', 'company_url'
])

# Настройки CAPTCHA
CAPTCHA_ENABLED = getattr(settings, 'CAPTCHA_ENABLED', False)
CAPTCHA_THRESHOLD = getattr(settings, 'CAPTCHA_THRESHOLD', 0.8)

# Настройки геолокации
GEOLOCATION_ENABLED = getattr(settings, 'GEOLOCATION_ENABLED', False)
GEOLOCATION_BLOCKED_COUNTRIES = getattr(settings, 'GEOLOCATION_BLOCKED_COUNTRIES', [])

# Настройки VPN/Proxy детекции
VPN_DETECTION_ENABLED = getattr(settings, 'VPN_DETECTION_ENABLED', False)
PROXY_DETECTION_ENABLED = getattr(settings, 'PROXY_DETECTION_ENABLED', False)

# Настройки машинного обучения
ML_ENABLED = getattr(settings, 'ML_ENABLED', False)
ML_MODEL_PATH = getattr(settings, 'ML_MODEL_PATH', None)
ML_CONFIDENCE_THRESHOLD = getattr(settings, 'ML_CONFIDENCE_THRESHOLD', 0.8)

# Экспорт всех настроек
SECURITY_SETTINGS = {
    # Основные
    'SECURITY_ENABLED': SECURITY_ENABLED,
    'SECURITY_DEBUG': SECURITY_DEBUG,
    
    # Middleware
    'SECURITY_MIDDLEWARE_ENABLED': SECURITY_MIDDLEWARE_ENABLED,
    'SECURITY_BLOCK_REQUESTS': SECURITY_BLOCK_REQUESTS,
    'SECURITY_CACHE_TIMEOUT': SECURITY_CACHE_TIMEOUT,
    
    # Пути
    'SECURITY_PROTECTED_PATHS': SECURITY_PROTECTED_PATHS,
    'SECURITY_EXCLUDED_PATHS': SECURITY_EXCLUDED_PATHS,
    
    # Rate limiting
    'SECURITY_MAX_REQUESTS_PER_MINUTE': SECURITY_MAX_REQUESTS_PER_MINUTE,
    'SECURITY_MAX_REQUESTS_PER_HOUR': SECURITY_MAX_REQUESTS_PER_HOUR,
    'SECURITY_MAX_REQUESTS_PER_DAY': SECURITY_MAX_REQUESTS_PER_DAY,
    
    # Отчеты
    'SECURITY_REPORT_MIDDLEWARE_ENABLED': SECURITY_REPORT_MIDDLEWARE_ENABLED,
    'SECURITY_AUTO_BLOCK_ENABLED': SECURITY_AUTO_BLOCK_ENABLED,
    'SECURITY_AUTO_BLOCK_THRESHOLD': SECURITY_AUTO_BLOCK_THRESHOLD,
    
    # Логирование
    'SECURITY_LOGGING_ENABLED': SECURITY_LOGGING_ENABLED,
    'SECURITY_LOG_LEVEL': SECURITY_LOG_LEVEL,
    
    # Device fingerprinting
    'DEVICE_FINGERPRINT_ENABLED': DEVICE_FINGERPRINT_ENABLED,
    'DEVICE_FINGERPRINT_MIN_CONFIDENCE': DEVICE_FINGERPRINT_MIN_CONFIDENCE,
    'DEVICE_FINGERPRINT_CACHE_TIMEOUT': DEVICE_FINGERPRINT_CACHE_TIMEOUT,
    
    # Поведенческий анализ
    'BEHAVIORAL_ANALYSIS_ENABLED': BEHAVIORAL_ANALYSIS_ENABLED,
    'BEHAVIORAL_ANALYSIS_MIN_EVENTS': BEHAVIORAL_ANALYSIS_MIN_EVENTS,
    'BEHAVIORAL_ANALYSIS_TIMEOUT': BEHAVIORAL_ANALYSIS_TIMEOUT,
    
    # Пороги риска
    'RISK_THRESHOLD_LOW': RISK_THRESHOLD_LOW,
    'RISK_THRESHOLD_MEDIUM': RISK_THRESHOLD_MEDIUM,
    'RISK_THRESHOLD_HIGH': RISK_THRESHOLD_HIGH,
    'RISK_THRESHOLD_CRITICAL': RISK_THRESHOLD_CRITICAL,
    
    # Обнаружение автоматизации
    'AUTOMATION_DETECTION_ENABLED': AUTOMATION_DETECTION_ENABLED,
    'AUTOMATION_DETECTION_STRICT': AUTOMATION_DETECTION_STRICT,
    'SUSPICIOUS_USER_AGENTS': SUSPICIOUS_USER_AGENTS,
    'AUTOMATION_USER_AGENTS': AUTOMATION_USER_AGENTS,
    
    # Черный список
    'BLACKLIST_ENABLED': BLACKLIST_ENABLED,
    'BLACKLIST_AUTO_EXPIRE': BLACKLIST_AUTO_EXPIRE,
    'BLACKLIST_DEFAULT_DURATION_HOURS': BLACKLIST_DEFAULT_DURATION_HOURS,
    
    # Мониторинг угроз
    'THREAT_MONITORING_ENABLED': THREAT_MONITORING_ENABLED,
    'THREAT_DETECTION_THRESHOLD': THREAT_DETECTION_THRESHOLD,
    'THREAT_AUTO_INVESTIGATION': THREAT_AUTO_INVESTIGATION,
    
    # Уведомления
    'SECURITY_NOTIFICATIONS_ENABLED': SECURITY_NOTIFICATIONS_ENABLED,
    'SECURITY_EMAIL_NOTIFICATIONS': SECURITY_EMAIL_NOTIFICATIONS,
    'SECURITY_WEBHOOK_URL': SECURITY_WEBHOOK_URL,
    
    # Производительность
    'SECURITY_ASYNC_PROCESSING': SECURITY_ASYNC_PROCESSING,
    'SECURITY_BATCH_SIZE': SECURITY_BATCH_SIZE,
    'SECURITY_CACHE_BACKEND': SECURITY_CACHE_BACKEND,
    
    # Очистка данных
    'SECURITY_DATA_RETENTION_DAYS': SECURITY_DATA_RETENTION_DAYS,
    'SECURITY_AUTO_CLEANUP_ENABLED': SECURITY_AUTO_CLEANUP_ENABLED,
    'SECURITY_CLEANUP_BATCH_SIZE': SECURITY_CLEANUP_BATCH_SIZE,
    
    # API
    'SECURITY_API_RATE_LIMIT': SECURITY_API_RATE_LIMIT,
    'SECURITY_API_AUTHENTICATION_REQUIRED': SECURITY_API_AUTHENTICATION_REQUIRED,
    'SECURITY_API_ADMIN_ONLY': SECURITY_API_ADMIN_ONLY,
    
    # Фронтенд
    'SECURITY_FRONTEND_ENABLED': SECURITY_FRONTEND_ENABLED,
    'SECURITY_FRONTEND_TIMEOUT': SECURITY_FRONTEND_TIMEOUT,
    'SECURITY_FRONTEND_RETRY_ATTEMPTS': SECURITY_FRONTEND_RETRY_ATTEMPTS,
    
    # Fingerprinting
    'CANVAS_FINGERPRINT_ENABLED': CANVAS_FINGERPRINT_ENABLED,
    'CANVAS_FINGERPRINT_TEXT': CANVAS_FINGERPRINT_TEXT,
    'WEBGL_FINGERPRINT_ENABLED': WEBGL_FINGERPRINT_ENABLED,
    'AUDIO_FINGERPRINT_ENABLED': AUDIO_FINGERPRINT_ENABLED,
    
    # Отслеживание поведения
    'MOUSE_TRACKING_ENABLED': MOUSE_TRACKING_ENABLED,
    'MOUSE_TRACKING_SAMPLE_RATE': MOUSE_TRACKING_SAMPLE_RATE,
    'MOUSE_TRACKING_MAX_EVENTS': MOUSE_TRACKING_MAX_EVENTS,
    'KEYSTROKE_TRACKING_ENABLED': KEYSTROKE_TRACKING_ENABLED,
    'KEYSTROKE_TRACKING_MAX_EVENTS': KEYSTROKE_TRACKING_MAX_EVENTS,
    'SCROLL_TRACKING_ENABLED': SCROLL_TRACKING_ENABLED,
    'SCROLL_TRACKING_THROTTLE': SCROLL_TRACKING_THROTTLE,
    'FOCUS_TRACKING_ENABLED': FOCUS_TRACKING_ENABLED,
    
    # Анализ времени
    'TIMING_ANALYSIS_ENABLED': TIMING_ANALYSIS_ENABLED,
    'MIN_FORM_FILL_TIME': MIN_FORM_FILL_TIME,
    'MAX_FORM_FILL_TIME': MAX_FORM_FILL_TIME,
    
    # Honeypot
    'HONEYPOT_ENABLED': HONEYPOT_ENABLED,
    'HONEYPOT_FIELD_NAMES': HONEYPOT_FIELD_NAMES,
    
    # CAPTCHA
    'CAPTCHA_ENABLED': CAPTCHA_ENABLED,
    'CAPTCHA_THRESHOLD': CAPTCHA_THRESHOLD,
    
    # Геолокация
    'GEOLOCATION_ENABLED': GEOLOCATION_ENABLED,
    'GEOLOCATION_BLOCKED_COUNTRIES': GEOLOCATION_BLOCKED_COUNTRIES,
    
    # VPN/Proxy
    'VPN_DETECTION_ENABLED': VPN_DETECTION_ENABLED,
    'PROXY_DETECTION_ENABLED': PROXY_DETECTION_ENABLED,
    
    # Машинное обучение
    'ML_ENABLED': ML_ENABLED,
    'ML_MODEL_PATH': ML_MODEL_PATH,
    'ML_CONFIDENCE_THRESHOLD': ML_CONFIDENCE_THRESHOLD,
}


def get_security_setting(key, default=None):
    """
    Получить настройку безопасности
    """
    return SECURITY_SETTINGS.get(key, default)


def is_security_enabled():
    """
    Проверить, включена ли система безопасности
    """
    return SECURITY_ENABLED


def get_risk_thresholds():
    """
    Получить пороги риска
    """
    return {
        'low': RISK_THRESHOLD_LOW,
        'medium': RISK_THRESHOLD_MEDIUM,
        'high': RISK_THRESHOLD_HIGH,
        'critical': RISK_THRESHOLD_CRITICAL
    }


def get_protected_paths():
    """
    Получить защищенные пути
    """
    return SECURITY_PROTECTED_PATHS


def get_excluded_paths():
    """
    Получить исключенные пути
    """
    return SECURITY_EXCLUDED_PATHS