# Generated by Django 5.2.4 on 2025-07-12 12:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL основного изображения')),
                ('images', models.TextField(blank=True, null=True, verbose_name='Дополнительные изображения (JSON)')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Предзаказ',
                'verbose_name_plural': 'Предзаказы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL изображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PreorderSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_name', models.CharField(max_length=50, verbose_name='Название размера')),
                ('size_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка размера')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество для заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='Распродано')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.preorder', verbose_name='Предзаказ')),
            ],
            options={
                'verbose_name': 'Размер предзаказа',
                'verbose_name_plural': 'Размеры предзаказов',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Цена')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для сравнения')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость')),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Вес')),
                ('dimensions', models.TextField(blank=True, null=True, verbose_name='Размеры (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('requires_shipping', models.BooleanField(default=True, verbose_name='Требует доставки')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Цифровой товар')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('low_stock_threshold', models.IntegerField(default=5, verbose_name='Порог малого запаса')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Отслеживать запасы')),
                ('allow_backorder', models.BooleanField(default=False, verbose_name='Разрешить предзаказ')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('search_keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова для поиска')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL основного изображения')),
                ('images', models.TextField(blank=True, null=True, verbose_name='Дополнительные изображения (JSON)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=500, verbose_name='URL изображения')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt текст')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_name', models.CharField(max_length=50, verbose_name='Название размера')),
                ('size_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метка размера')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('max_quantity', models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество для заказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_sold_out', models.BooleanField(default=False, verbose_name='Распродано')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Размер товара',
                'verbose_name_plural': 'Размеры товаров',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для сравнения')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Себестоимость')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('variant_options', models.TextField(verbose_name='Опции варианта (JSON)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Содержание')),
                ('is_verified_purchase', models.BooleanField(default=False, verbose_name='Подтвержденная покупка')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Счетчик полезности')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о товаре',
                'verbose_name_plural': 'Отзывы о товарах',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
