# Generated by Django 5.2.4 on 2025-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preordersize',
            name='stock_quantity',
            field=models.IntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
