# Generated by Django 5.2.4 on 2025-07-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_preordersize_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=100000, verbose_name='URL изображения'),
        ),
    ]
