# Generated by Django 5.2.4 on 2025-07-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_change_imagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.TextField(blank=True, verbose_name='URL изображения'),
        ),
    ]
