# Generated by Django 5.2.4 on 2025-07-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядок сортировки'),
        ),
    ]
