# Generated by Django 5.2.4 on 2025-07-25 12:00

import djmoney.models.fields
from django.db import migrations
from decimal import Decimal
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_preorder_price_currency_and_more'),
    ]

    operations = [
        # Обновляем поля валют для ограничения только рублем
        migrations.AlterField(
            model_name='preorder',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='compare_price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
    ]
