# Generated by Django 5.2.4 on 2025-07-25 12:12

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20250725_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='compare_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3, null=True),
        ),
    ]
