# Generated by Django 5.2.4 on 2025-07-25 16:57

import apps.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_preorder_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Описание изображения для поисковых систем и доступности', max_length=255, null=True, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF. Максимальный размер: 5MB. Минимальный размер: 100x100px.', null=True, upload_to=apps.products.models.product_image_upload_path, validators=[apps.products.models.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернатива загрузке файла - укажите прямую ссылку на изображение', max_length=500, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Отметьте для установки в качестве основного изображения товара', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, help_text='Порядок отображения (меньшее число = выше в списке)', verbose_name='Порядок сортировки'),
        ),
    ]
