# Generated by Django 5.2.4 on 2025-07-26 06:44

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_preorderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Предзаказ', 'verbose_name_plural': 'Предзаказы'},
        ),
        migrations.AlterModelOptions(
            name='preorderimage',
            options={'ordering': ['sort_order'], 'verbose_name': 'Изображение предзаказа', 'verbose_name_plural': 'Изображения предзаказов'},
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='preorder',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='preorder',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
