# Generated by Django 5.2.4 on 2025-07-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_preorder_price_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorderimage',
            name='image_type',
            field=models.CharField(choices=[('model', 'Изображение модели'), ('product', 'Изображение товара'), ('additional', 'Дополнительное изображение')], default='additional', help_text='Выберите тип изображения: модель, товар или дополнительное', max_length=20, verbose_name='Тип изображения'),
        ),
    ]
