# Generated by Django 5.2.4 on 2025-07-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_preorderimage_image_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
