# Generated by Django 5.2.4 on 2025-07-26 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='images',
        ),
    ]
