# Generated by Django 5.2.4 on 2025-07-26 07:19

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20250726_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorderimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.products.models.preorder_image_upload_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='image_type',
            field=models.CharField(choices=[('model', 'Модель'), ('product', 'Товар'), ('additional', 'Дополнительное')], default='additional', max_length=20, verbose_name='Тип изображения'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
    ]
