# Generated by Django 5.2.4 on 2025-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_preorderimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Максимальное количество данного размера, которое можно добавить в корзину', null=True, verbose_name='Ограничение для корзины'),
        ),
    ]
