# Generated by Django 5.2.4 on 2025-07-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productsize_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
