# Generated by Django 5.2.4 on 2025-09-02 13:54

import apps.products.models
import apps.products.validators.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_max_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF. Максимальный размер: 10MB. Минимальный размер: 100x100px.', null=True, upload_to=apps.products.models.product_image_upload_path, validators=[apps.products.validators.image_validator.ImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='preorderimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF. Максимальный размер: 10MB. Минимальный размер: 100x100px.', null=True, upload_to=apps.products.models.preorder_image_upload_path, verbose_name='Изображение'),
        ),
    ]
