# Generated by Django 5.2.4 on 2025-09-08 07:32

import apps.products.models
import apps.products.validators.image_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_productimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='limit',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF. Максимальный размер: 10MB. Минимальный размер: 100x100px.', null=True, upload_to=apps.products.models.product_image_upload_path, validators=[apps.products.validators.image_validator.ImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF')], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='max_quantity',
            field=models.IntegerField(blank=True, help_text='Максимальное количество данного размера, которое можно добавить в заказ', null=True, verbose_name='Лимит для заказа'),
        ),
    ]
