# Generated by Django 5.2.8 on 2025-12-01 10:48

import apps.products.models
import apps.products.validators.image_validator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF. Максимальный размер: 10MB. Минимальный размер: 100x100px.', null=True, upload_to=apps.products.models.product_image_upload_path, validators=[apps.products.validators.image_validator.ImageValidator.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP, GIF')], verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='PreorderColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('hex_code', models.CharField(help_text='Например: #FF0000 для красного', max_length=7, verbose_name='HEX код цвета')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('preorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.preorder', verbose_name='Предзаказ')),
            ],
            options={
                'verbose_name': 'Цвет предзаказа',
                'verbose_name_plural': 'Цвета предзаказов',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Название цвета')),
                ('hex_code', models.CharField(help_text='Например: #FF0000 для красного', max_length=7, verbose_name='HEX код цвета')),
                ('stock_quantity', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Цвет товара',
                'verbose_name_plural': 'Цвета товаров',
                'ordering': ['sort_order'],
            },
        ),
    ]
