# Generated by Django 5.2.4 on 2025-07-12 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('processing', 'Обрабатывается'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('fulfillment_status', models.CharField(choices=[('unfulfilled', 'Не выполнен'), ('partially_fulfilled', 'Частично выполнен'), ('fulfilled', 'Выполнен'), ('restocked', 'Возвращен на склад')], default='unfulfilled', max_length=20, verbose_name='Статус выполнения')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Промежуточная сумма')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Налог')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Скидка')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Адрес оплаты')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('shipping_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метод доставки')),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True, verbose_name='Метод оплаты')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер отслеживания')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('item_type', models.CharField(choices=[('product', 'Товар'), ('preorder', 'Предзаказ')], default='product', max_length=20, verbose_name='Тип элемента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'ordering': ['id'],
            },
        ),
    ]
