# Generated by Django 5.2.4 on 2025-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address_text',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес оплаты (текст)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_text',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки (текст)'),
        ),
    ]
