# Generated by Django 5.2.4 on 2025-07-13 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
        ('orders', '0004_order_billing_address_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_address_text',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address_text',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='addresses.address', verbose_name='Адрес оплаты (объект)'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='addresses.address', verbose_name='Адрес доставки (объект)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес оплаты (текст)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки (текст)'),
        ),
    ]
