# Generated by Django 5.2.4 on 2025-07-25 12:02

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_discount_currency_order_shipping_currency_and_more'),
    ]

    operations = [
        # Обновляем поля валют для ограничения только рублем
        migrations.AlterField(
            model_name='order',
            name='discount_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
    ]
