# Generated by Django 5.2.4 on 2025-07-25 16:57

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20250725_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
    ]
