# Generated by Django 5.2.4 on 2025-07-26 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_reservation_cartitem_reservation_and_more'),
        ('orders', '0008_alter_order_discount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.reservation', verbose_name='Резервирование'),
        ),
    ]
