# Generated by Django 5.2.4 on 2025-07-27 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_historicaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram Verified'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, verbose_name='Telegram Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Username'),
        ),
        migrations.CreateModel(
            name='TelegramVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Verification Code')),
                ('telegram_chat_id', models.CharField(max_length=50, verbose_name='Telegram Chat ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('verification_type', models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('login', 'Login')], default='registration', max_length=20, verbose_name='Verification Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Telegram Verification Code',
                'verbose_name_plural': 'Telegram Verification Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
