# Generated by Django 4.2.23 on 2025-07-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguserregistration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='Verification Code'),
        ),
    ]
