# Generated by Django 4.2.23 on 2025-07-27 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_telegramverificationcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR Code ID')),
                ('trigger_url', models.URLField(max_length=500, verbose_name='Trigger URL')),
                ('telegram_bot_url', models.URLField(max_length=500, verbose_name='Telegram Bot URL')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Scanned At')),
                ('trigger_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Trigger Activated At')),
                ('bot_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bot Started At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Scan Count')),
                ('successful_activations', models.PositiveIntegerField(default=0, verbose_name='Successful Activations')),
                ('verification_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='accounts.telegramverificationcode')),
            ],
            options={
                'verbose_name': 'QR Code Scan',
                'verbose_name_plural': 'QR Code Scans',
                'ordering': ['-created_at'],
            },
        ),
    ]
