# Generated by Django 4.2.23 on 2025-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_qrcodescan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='verification_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('password_reset', 'Password Reset'), ('login', 'Login'), ('qr_registration', 'QR Registration')], default='registration', max_length=20, verbose_name='Verification Type'),
        ),
    ]
