# Generated by Django 5.2.4 on 2025-07-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_telegramverificationcode_verification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
