# Generated by Django 5.2.4 on 2025-07-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_telegramverificationcode_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Used At'),
        ),
    ]
