# Generated by Django 5.2.4 on 2025-07-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_used_at_to_telegram_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telegram Phone Number'),
        ),
    ]
