# Generated by Django 5.2.4 on 2025-07-30 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_telegram_phone_to_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodescan',
            name='pending_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qr_scans', to='accounts.pendinguserregistration'),
        ),
    ]
