# Generated by Django 5.2.4 on 2025-08-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='code_hash',
            field=models.CharField(max_length=64, null=True, blank=True, help_text='SHA-256 хеш кода верификации'),
        ),
        migrations.AddField(
            model_name='telegramverificationcode',
            name='salt',
            field=models.CharField(max_length=64, null=True, blank=True, help_text='Случайная соль для хеширования'),
        ),
    ]
