# Generated by Django 5.2.4 on 2025-08-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_telegram_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество попыток ввода кода', verbose_name='Количество попыток'),
        ),
    ]