# Generated by Django 5.2.4 on 2025-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_attempts_count_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True, verbose_name='IP адрес'),
        ),
    ]