# Generated by Django 5.2.4 on 2025-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_ip_address_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]