# Generated by Django 5.2.4 on 2025-08-27 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_make_telegram_chat_id_nullable'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaluser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Пользователь', 'verbose_name_plural': 'historical Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='telegramverificationcode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Код верификации Telegram', 'verbose_name_plural': 'Коды верификации Telegram'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='address',
            field=models.TextField(blank=True, help_text='Полный почтовый адрес', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, help_text='Обязательное поле. Введите действующий email адрес.', max_length=254, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя пользователя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, help_text='Подтверждена ли связь с Telegram аккаунтом', verbose_name='Telegram верифицирован'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона в международном формате', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Уникальный ID чата в Telegram', null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username пользователя в Telegram (без @)', max_length=100, verbose_name='Telegram Username'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='attempts_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество попыток'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='code',
            field=models.CharField(blank=True, help_text='6-значный код верификации', max_length=6, null=True, verbose_name='Код верификации'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='code_hash',
            field=models.CharField(blank=True, help_text='SHA-256 хеш кода верификации', max_length=64, null=True, verbose_name='Хеш кода'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Истекает'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='pending_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_verification_codes', to='accounts.pendinguserregistration'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='salt',
            field=models.CharField(blank=True, help_text='Случайная соль для хеширования', max_length=64, null=True, verbose_name='Соль'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='telegram_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telegram Phone'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использован в'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='verification_type',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('login', 'Вход в систему'), ('password_reset', 'Сброс пароля'), ('qr_registration', 'QR регистрация'), ('phone_change_current', 'Подтверждение текущего номера'), ('phone_change_new', 'Подтверждение нового номера')], default='registration', max_length=30, verbose_name='Тип верификации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Полный почтовый адрес', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Обязательное поле. Введите действующий email адрес.', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Имя пользователя', max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_telegram_verified',
            field=models.BooleanField(default=False, help_text='Подтверждена ли связь с Telegram аккаунтом', verbose_name='Telegram верифицирован'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Фамилия пользователя', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Номер телефона в международном формате', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Уникальный ID чата в Telegram', null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username пользователя в Telegram (без @)', max_length=100, verbose_name='Telegram Username'),
        ),
        migrations.AddIndex(
            model_name='telegramverificationcode',
            index=models.Index(fields=['user', 'verification_type'], name='accounts_te_user_id_3cf0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramverificationcode',
            index=models.Index(fields=['expires_at'], name='accounts_te_expires_496ac4_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramverificationcode',
            index=models.Index(fields=['is_used', 'created_at'], name='accounts_te_is_used_d1066c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='accounts_us_email_f69303_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['telegram_chat_id'], name='accounts_us_telegra_715fd4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_telegram_verified'], name='accounts_us_is_tele_b038e5_idx'),
        ),
    ]
