# Generated by Django 5.2.4 on 2025-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_historicaluser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username пользователя в Telegram (без @)', max_length=100, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Username пользователя в Telegram (без @)', max_length=100, null=True, verbose_name='Telegram Username'),
        ),
    ]
