# Generated by Django 5.2.4 on 2025-09-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_historicaluser_telegram_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramverificationcode',
            name='verification_type',
            field=models.CharField(choices=[('registration', 'Регистрация'), ('login', 'Вход в систему'), ('password_reset', 'Сброс пароля'), ('qr_registration', 'QR регистрация'), ('telegram_registration', 'Регистрация через Telegram'), ('phone_change_current', 'Подтверждение текущего номера'), ('phone_change_new', 'Подтверждение нового номера')], default='registration', max_length=30, verbose_name='Тип верификации'),
        ),
    ]
