# Generated by Django 5.2.4 on 2025-09-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_telegramverificationcode_verification_type'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_historicaluser ADD COLUMN phone VARCHAR(20) DEFAULT '';",
            reverse_sql="ALTER TABLE accounts_historicaluser DROP COLUMN phone;"
        ),
    ]
