# Generated by Django 5.2.4 on 2025-09-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_phone_to_historical_user'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_historicaluser ADD COLUMN address VARCHAR(255) DEFAULT '';",
            reverse_sql="ALTER TABLE accounts_historicaluser DROP COLUMN address;"
        ),
    ]
