# Generated by Django 5.2.4 on 2025-09-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_address_to_historical_user'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_historicaluser ADD COLUMN telegram_chat_id BIGINT;",
            reverse_sql="ALTER TABLE accounts_historicaluser DROP COLUMN telegram_chat_id;"
        ),
    ]
