# Generated by Django 5.2.4 on 2025-09-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_telegram_chat_id_to_historical_user'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_historicaluser ADD COLUMN telegram_username VARCHAR(150);",
            reverse_sql="ALTER TABLE accounts_historicaluser DROP COLUMN telegram_username;"
        ),
    ]
