# Generated by Django 5.2.4 on 2025-09-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_add_telegram_username_to_historical_user'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE accounts_historicaluser ADD COLUMN is_telegram_verified BOOLEAN DEFAULT 0;",
            "ALTER TABLE accounts_historicaluser DROP COLUMN is_telegram_verified;"
        ),
    ]
