# Generated by Django 5.2.4 on 2025-07-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Адрес оплаты'), ('shipping', 'Адрес доставки')], default='shipping', max_length=10, verbose_name='Тип адреса')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Компания')),
                ('address_line1', models.CharField(max_length=255, verbose_name='Адрес строка 1')),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес строка 2')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион/Область')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Почтовый индекс')),
                ('country', models.CharField(default='Russia', max_length=100, verbose_name='Страна')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'address_type'], name='addresses_a_user_id_1792d5_idx'), models.Index(fields=['is_default', 'is_active'], name='addresses_a_is_defa_eae76b_idx')],
            },
        ),
    ]
