"""
Django settings for guscha_project project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import json
from pathlib import Path
from dotenv import load_dotenv
from str2bool import str2bool
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные окружения из .env файла
load_dotenv(BASE_DIR / '.env')  # Явно указываем путь к .env файлу


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is required")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str2bool(os.environ.get('DEBUG', 'False'))

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',  # Django Unfold для красивой админки
    'unfold.contrib.filters',  # Опциональные фильтры
    'unfold.contrib.forms',  # Опциональные формы
    'unfold.contrib.import_export',  # Импорт/экспорт для Unfold
    'unfold.contrib.simple_history',  # История для Unfold
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Сторонние приложения
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django_filters',
    'corsheaders',
    # 'crispy_forms',  # Временно отключено для отладки
    # 'crispy_tailwind',  # Временно отключено для отладки
    # 'import_export',  # Временно отключено для отладки
    'djmoney',  # Django Money для работы с валютами
    'defender',  # Защита от brute force атак
    'django_ratelimit',  # Ограничение частоты запросов
    'honeypot',  # Защита от ботов
    
    # Google OAuth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # dj-rest-auth для API аутентификации
    'dj_rest_auth',
    'dj_rest_auth.registration',

    
    # Приложения проекта
    'apps.products.apps.ProductsConfig',
    'apps.accounts.apps.AccountsConfig',
    'apps.orders.apps.OrdersConfig',
    'apps.cart.apps.CartConfig',
    'apps.core.apps.CoreConfig',
    'apps.addresses.apps.AddressesConfig',
    'apps.collections.apps.CollectionsConfig',
    'apps.background_content.apps.BackgroundContentConfig',
    'telegram_bot',

]

# Добавляем новые приложения для безопасности
INSTALLED_APPS += [
    'guardian',
    'django_recaptcha',
    'simple_history',  # История изменений моделей
]

# Минимальный набор middleware для тестов
if 'test' in sys.argv:
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'allauth.account.middleware.AccountMiddleware',
    ]
else:
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'csp.middleware.CSPMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        # 'corsheaders.middleware.CorsMiddleware',  # Временно отключено для тестов
        'apps.core.middleware.SecurityMonitoringMiddleware',  # Security monitoring
        'apps.core.middleware.SecurityMetricsMiddleware',  # Security metrics
        'apps.core.middleware.RateLimitBypassMiddleware',  # Before rate limiting
        'apps.core.middleware.RateLimitMiddleware',  # Rate limiting
        'django.middleware.common.CommonMiddleware',
        'apps.core.middleware.csrf_exempt.TelegramCSRFExemptMiddleware',  # CSRF exempt for Telegram
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'defender.middleware.FailedLoginMiddleware',
        'simple_history.middleware.HistoryRequestMiddleware',  # Middleware для simple_history
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
        'apps.core.middleware.SecurityHeadersMiddleware',
        'apps.core.middleware.SecurityAuditMiddleware',  # Security audit
        'allauth.account.middleware.AccountMiddleware',
    ]

ROOT_URLCONF = 'guscha_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'guscha_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Используем PostgreSQL в Docker окружении, SQLite локально
if os.getenv('DATABASE_URL') or os.getenv('POSTGRES_DB'):
    import psycopg2.extensions
    # PostgreSQL конфигурация для Docker
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'guscha_dev'),
            'USER': os.getenv('POSTGRES_USER', 'guscha'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'guscha123'),
            'HOST': os.getenv('POSTGRES_HOST', 'db'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'OPTIONS': {
                'isolation_level': psycopg2.extensions.ISOLATION_LEVEL_READ_COMMITTED,
            },
            'CONN_MAX_AGE': 600,  # Connection pooling
        }
    }
else:
    # SQLite конфигурация для локальной разработки
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static_root'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Добавляем версионирование статических файлов для принудительного обновления кеша
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
FILE_UPLOAD_PERMISSIONS = 0o644
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Sites Framework
SITE_ID = 1

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://redis:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Telegram Bot Settings
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', 'GuschaBot')

# Allauth settings
ACCOUNT_EMAIL_VERIFICATION = 'none'
# Новый API для методов входа (заменяет ACCOUNT_AUTHENTICATION_METHOD)
ACCOUNT_LOGIN_METHODS = {'email'}
# Заменяет ACCOUNT_EMAIL_REQUIRED и ACCOUNT_USERNAME_REQUIRED
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']

# Google OAuth settings
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_CLIENT_SECRET', '')

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'VERIFIED_EMAIL': True,
    }
}

ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'

# Пользовательская модель аутентификации
AUTH_USER_MODEL = 'accounts.User'

# Настройки dj-rest-auth
REST_USE_JWT = True
JWT_AUTH_COOKIE = 'jwt-auth'
JWT_AUTH_REFRESH_COOKIE = 'jwt-refresh'
REST_AUTH_SERIALIZERS = {
    'USER_DETAILS_SERIALIZER': 'apps.accounts.serializers.UserSerializer',
}
REST_AUTH_REGISTER_SERIALIZERS = {
    'REGISTER_SERIALIZER': 'apps.accounts.serializers.CustomRegisterSerializer',
}

# Настройки Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

# JWT Settings
from datetime import timedelta

# JWT Secret Key (отдельный от основного SECRET_KEY для безопасности)
JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', SECRET_KEY)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Сокращено для безопасности
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,  # Включено для аудита

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': JWT_SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

# Настройки CORS
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Только для разработки

# Получаем разрешенные origins из переменных окружения
CORS_ALLOWED_ORIGINS_ENV = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if CORS_ALLOWED_ORIGINS_ENV:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_ENV.split(',')]
else:
    # Fallback для продакшена
    CORS_ALLOWED_ORIGINS = [
        "https://yourdomain.com",
        "https://www.yourdomain.com",
    ]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
CORS_ALLOW_HEADERS = ['Content-Type', 'Authorization', 'X-CSRF-Token', 'X-CSRFToken', 'X-Session-ID']

# Настройки CSRF - используем те же origins что и для CORS
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS if not DEBUG else [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:80",
    "http://localhost",
    "http://127.0.0.1:80",
    "http://127.0.0.1",
]
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_HEADER_NAME = 'HTTP_X_CSRF_TOKEN'

# Дополнительные настройки CORS для разработки
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:80",
    "http://localhost",
    "http://127.0.0.1:80",
    "http://127.0.0.1",
]

# Настройки безопасности
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
X_FRAME_OPTIONS = 'SAMEORIGIN'

# Отключаем HSTS и SSL redirect для локальной разработки
SECURE_HSTS_SECONDS = 0
SECURE_SSL_REDIRECT = False

# Исправление 5: Добавить заголовки безопасности для продакшена
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Исправление 6: Настройки сессий для e-commerce
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 1800  # 30 минут для e-commerce безопасности
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'  # Защита от CSRF
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # Разрешаем JavaScript доступ к CSRF токену для фронтенда

# Создаем директорию для логов если она не существует
import os
LOGS_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'security': {
            'format': '[SECURITY] {asctime} {levelname} {name} - {message}',
            'style': '{',
        },
        'audit': {
            'format': '[AUDIT] {asctime} {levelname} - {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'security.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'security',
        },
        'audit_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'audit.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'audit',
        },
        'threat_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'threats.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 10,
            'formatter': 'security',
        },
        'error_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'errors.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        # Security monitoring loggers
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security.monitoring': {
            'handlers': ['security_file', 'threat_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'security.audit': {
            'handlers': ['audit_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security.threats': {
            'handlers': ['threat_file', 'mail_admins'],
            'level': 'WARNING',
            'propagate': False,
        },
        'security.authentication': {
            'handlers': ['security_file', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security.authorization': {
            'handlers': ['security_file', 'audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'security.ratelimit': {
            'handlers': ['security_file', 'threat_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django security loggers
        'django.security': {
            'handlers': ['security_file', 'mail_admins'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.security.csrf': {
            'handlers': ['security_file', 'threat_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Django Axes logger
        'axes': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # Application loggers
        'apps.products': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.products.admin': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.products.models': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.products.forms': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.accounts': {
            'handlers': ['console', 'file', 'audit_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'apps.accounts.views': {
            'handlers': ['console', 'file', 'audit_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'unfold': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}




# Настройки для reCAPTCHA
RECAPTCHA_PUBLIC_KEY = os.environ.get('RECAPTCHA_PUBLIC_KEY', 'your-public-key-here')
RECAPTCHA_PRIVATE_KEY = os.environ.get('RECAPTCHA_PRIVATE_KEY', 'your-private-key-here')

# Настройки для ratelimit
RATELIMIT_ENABLE = True

# Rate Limiting Configuration
RATE_LIMITING_ENABLED = True
RATE_LIMIT_IN_DEBUG = True  # Enable rate limiting in DEBUG mode for testing
RATE_LIMIT_SKIP_SUPERUSER = True  # Skip rate limiting for superusers

# Paths excluded from rate limiting
RATE_LIMIT_EXCLUDED_PATHS = [
    '/admin/jsi18n/',
    '/static/',
    '/media/',
    '/favicon.ico',
    '/health/',
    '/ping/',
    '/admin/login/',  # Allow admin login without rate limiting
]

# User agents excluded from rate limiting (bots, monitoring)
RATE_LIMIT_EXCLUDED_USER_AGENTS = [
    'GoogleBot',
    'BingBot',
    'YandexBot',
    'facebookexternalhit',
    'Twitterbot',
    'LinkedInBot',
    'WhatsApp',
    'Telegram',
    'UptimeRobot',
    'Pingdom',
]

# Trusted IPs that bypass rate limiting (monitoring, load balancers)
RATE_LIMIT_TRUSTED_IPS = [
    '127.0.0.1',
    '::1',
    # Add your monitoring server IPs here
    # '10.0.0.1',
    # '192.168.1.100',
]

# API keys that bypass rate limiting (for trusted integrations)
RATE_LIMIT_BYPASS_API_KEYS = [
    # Add trusted API keys here
    # 'monitoring-api-key-here',
    # 'integration-api-key-here',
]

# Дополнительные настройки безопасности
# SECURE_SSL_REDIRECT уже установлен выше в строке 230
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Authentication backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',  # Default backend
    'guardian.backends.ObjectPermissionBackend',  # Guardian backend для объектных разрешений
    'allauth.account.auth_backends.AuthenticationBackend',  # Allauth backend
)

# Настройки для crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Конфигурация Django Unfold
UNFOLD = {
    "SITE_TITLE": "Guscha Admin",
    "SITE_HEADER": "Панель управления Guscha",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: static("images/logo-light.svg"),  # Светлая тема
        "dark": lambda request: static("images/logo-dark.svg"),  # Тёмная тема
    },
    "SITE_LOGO": {
        "light": lambda request: static("images/logo-light.svg"),  # Светлая тема
        "dark": lambda request: static("images/logo-dark.svg"),  # Тёмная тема
    },
    "SITE_SYMBOL": "speed",  # Иконка Material Design
    "SHOW_HISTORY": True,  # Показывать историю изменений
    "SHOW_VIEW_ON_SITE": True,  # Показывать ссылку "Посмотреть на сайте"
    "SHOW_SAVE_AND_CONTINUE": True,  # Показывать кнопку "Сохранить и продолжить"
    "ENVIRONMENT": "guscha_project.settings.environment_callback",
    "DASHBOARD_CALLBACK": "guscha_project.settings.dashboard_callback",
    "LOGIN": {
        "image": lambda request: static("images/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [
        # lambda request: static("admin/css/custom-admin.css"),  # Временно отключено для отладки
    ],
    "SCRIPTS": [
        # lambda request: static("admin/js/fix_inline_buttons.js"),  # Временно отключено для отладки
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "196 144 254",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,  # Показывать поиск в сайдбаре
        "show_all_applications": True,  # Показывать все приложения
        "navigation": [
            {
                "title": _("Навигация"),
                "separator": True,  # Разделитель
                "items": [
                    {
                        "title": _("Дашборд"),
                        "icon": "dashboard",  # Иконка Material Design
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": _("Пользователи"),
                        "icon": "people",
                        "link": reverse_lazy("admin:accounts_user_changelist"),
                    },
                    {
                        "title": _("Товары"),
                        "icon": "inventory",
                        "link": reverse_lazy("admin:products_product_changelist"),
                    },
                    {
                        "title": _("Предзаказы"),
                        "icon": "schedule",
                        "link": reverse_lazy("admin:products_preorder_changelist"),
                    },
                    {
                        "title": _("Заказы"),
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:orders_order_changelist"),
                    },
                    {
                        "title": _("Резервирования"),
                        "icon": "bookmark",
                        "link": reverse_lazy("admin:cart_reservation_changelist"),
                    },
                    {
                         "title": _("Фоновый контент"),
                         "icon": "image",
                         "link": "http://localhost/admin/background_content/",
                     },
                    {
                        "title": _("Коллекции"),
                        "icon": "collections",
                        "link": reverse_lazy("admin:collections_collection_changelist"),
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "accounts.user",
            ],
            "items": [
                {
                    "title": _("Пользователи"),
                    "link": reverse_lazy("admin:accounts_user_changelist"),
                },
                {
                    "title": _("Группы"),
                    "link": reverse_lazy("admin:auth_group_changelist"),
                },
            ],
        },
    ],
}

# Функции обратного вызова для Unfold
def environment_callback(request):
    """Определяет окружение для отображения в админке"""
    return "Разработка" if DEBUG else "Продакшн"

def dashboard_callback(request, context):
    """Добавляет данные для дашборда"""
    from django.contrib.auth import get_user_model
    from apps.products.models import Product, Category
    from apps.orders.models import Order, OrderItem
    from django.utils import timezone
    from datetime import timedelta
    from django.db.models import Sum, Count
    from decimal import Decimal
    
    User = get_user_model()
    
    # Базовая статистика
    total_users = User.objects.count()
    total_products = Product.objects.count()
    total_orders = Order.objects.count()
    orders_today = Order.objects.filter(created_at__date=timezone.now().date()).count()
    
    # Общая выручка
    total_revenue = Order.objects.filter(status='completed').aggregate(
        total=Sum('total')
    )['total'] or Decimal('0')
    
    # Данные для графика выручки за последние 30 дней
    end_date = timezone.now().date()
    start_date = end_date - timedelta(days=29)
    
    revenue_data = []
    labels = []
    
    for i in range(30):
        date = start_date + timedelta(days=i)
        daily_revenue = Order.objects.filter(
            created_at__date=date,
            status='completed'
        ).aggregate(total=Sum('total'))['total'] or Decimal('0')
        
        revenue_data.append(float(daily_revenue))
        labels.append(date.strftime('%d.%m'))
    
    # Данные для графика регистраций пользователей за последние 30 дней
    users_data = []
    
    for i in range(30):
        date = start_date + timedelta(days=i)
        daily_users = User.objects.filter(date_joined__date=date).count()
        users_data.append(daily_users)
    
    # Данные для графика заказов по категориям
    categories_data = []
    categories_labels = []
    
    categories_stats = Category.objects.annotate(
        order_count=Count('products__orderitem', distinct=True)
    ).filter(order_count__gt=0).order_by('-order_count')[:10]
    
    for category in categories_stats:
        categories_data.append(category.order_count)
        categories_labels.append(category.name)
    
    # Последние заказы для таблицы
    recent_orders = Order.objects.select_related('user').order_by('-created_at')[:10]
    
    # Формирование данных для графиков в формате Chart.js
    revenue_chart_data = {
        'labels': labels,
        'datasets': [{
            'label': 'Выручка (₽)',
            'data': revenue_data,
            'borderColor': 'rgb(168, 85, 247)',
            'backgroundColor': 'rgba(168, 85, 247, 0.1)',
            'tension': 0.4,
            'fill': True
        }]
    }
    
    users_chart_data = {
        'labels': labels,
        'datasets': [{
            'label': 'Регистрации',
            'data': users_data,
            'backgroundColor': 'rgba(59, 130, 246, 0.8)',
            'borderColor': 'rgb(59, 130, 246)',
            'borderWidth': 1
        }]
    }
    
    orders_by_category_data = {
        'labels': categories_labels,
        'datasets': [{
            'label': 'Количество заказов',
            'data': categories_data,
            'backgroundColor': [
                'rgba(168, 85, 247, 0.8)',
                'rgba(59, 130, 246, 0.8)',
                'rgba(16, 185, 129, 0.8)',
                'rgba(245, 158, 11, 0.8)',
                'rgba(239, 68, 68, 0.8)',
                'rgba(139, 92, 246, 0.8)',
                'rgba(236, 72, 153, 0.8)',
                'rgba(34, 197, 94, 0.8)',
                'rgba(251, 146, 60, 0.8)',
                'rgba(14, 165, 233, 0.8)'
            ],
            'borderWidth': 1
        }]
    }
    
    # Данные для таблицы последних заказов
    recent_orders_table = {
        'headers': ['№ заказа', 'Пользователь', 'Сумма', 'Статус', 'Дата'],
        'rows': []
    }
    
    for order in recent_orders:
        recent_orders_table['rows'].append([
            f'#{order.id}',
            (order.user.get_full_name() or order.user.email) if order.user else 'Гость',
            f'{order.total} ₽',
            order.get_status_display(),
            order.created_at.strftime('%d.%m.%Y %H:%M')
        ])
    
    context.update({
        'total_users': total_users,
        'total_revenue': f'{total_revenue:,.0f} ₽',
        'orders_today': orders_today,
        'products_count': total_products,
        'revenue_chart_data': json.dumps(revenue_chart_data, ensure_ascii=False),
        'users_chart_data': json.dumps(users_chart_data, ensure_ascii=False),
        'orders_by_category_data': json.dumps(orders_by_category_data, ensure_ascii=False),
        'recent_orders': recent_orders,
        'recent_orders_table': recent_orders_table,
    })
    return context


# Настройки django-money
CURRENCIES = ('RUB',)  # Ограничиваем только рублем
DEFAULT_CURRENCY = 'RUB'
CURRENCY_CHOICES = [('RUB', 'Рубль')]

# Дополнительные настройки для django-money
USE_MONEY_LOCALIZATION = True
MONEY_DECIMAL_PLACES = 2
MONEY_MAX_DIGITS = 10

# Настройки Email для сброса пароля
# Для локальной разработки используем консольный бэкенд
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Для продакшена настройки SMTP (Beget)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.beget.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = str2bool(os.environ.get('EMAIL_USE_TLS', 'True'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Общие настройки email
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@guscha.ru')
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_SUBJECT_PREFIX = '[Guscha] '

# Настройки для сброса пароля
PASSWORD_RESET_TIMEOUT = 3600  # 1 час в секундах

# Настройки Telegram бота
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')

# URL фронтенда для генерации ссылок (для статических файлов)
# Поскольку фронтенд собирается в статические файлы и обслуживается Django
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:8000')

# Content Security Policy настройки
# Разные политики для разработки и продакшена
if DEBUG:
    # Разрешительная политика для разработки (включая админку)
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
    CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
    CSP_IMG_SRC = ("'self'", "data:", "blob:")
    CSP_FONT_SRC = ("'self'", "data:")
    CSP_CONNECT_SRC = ("'self'",)
    CSP_FRAME_SRC = ("'self'",)
    CSP_MEDIA_SRC = ("'self'",)
else:
    # Строгая политика для продакшена БЕЗ unsafe-inline и unsafe-eval
    CSP_DEFAULT_SRC = ("'self'",)
    CSP_SCRIPT_SRC = ("'self'", "https://accounts.google.com", "https://apis.google.com")
    CSP_STYLE_SRC = ("'self'", "https://fonts.googleapis.com")
    CSP_IMG_SRC = ("'self'", "data:", "https:")
    CSP_FONT_SRC = ("'self'", "https://fonts.gstatic.com")
    CSP_CONNECT_SRC = ("'self'", "https://accounts.google.com", "https://apis.google.com")
    CSP_FRAME_SRC = ("'self'", "https://accounts.google.com")

# Настройки Django Defender
DEFENDER_REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/1')
DEFENDER_LOGIN_FAILURE_LIMIT = 5
DEFENDER_COOLOFF_TIME = 300  # 5 минут
DEFENDER_LOCKOUT_TEMPLATE = 'defender/lockout.html'
DEFENDER_STORE_ACCESS_ATTEMPTS = True
DEFENDER_USE_CELERY = False  # Отключаем Celery, так как он не установлен
DEFENDER_LOCKOUT_URL = '/api/auth/lockout/'
DEFENDER_REVERSE_PROXY_HEADER = 'HTTP_X_FORWARDED_FOR'

# Дополнительные CSP настройки
CSP_MEDIA_SRC = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)

# Настройки Django Axes (защита от brute force) - УСТАРЕЛО, используем defender
# AXES_FAILURE_LIMIT = 5
# AXES_COOLOFF_TIME = 1  # час
# AXES_RESET_ON_SUCCESS = True

# Настройки Django Ratelimit
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_VIEW = 'django_ratelimit.views.ratelimited'

# Кастомные настройки для разных типов запросов
API_RATELIMIT_RATE = '100/h'  # 100 запросов в час для API
AUTH_RATELIMIT_RATE = '10/m'  # 10 попыток входа в минуту
REGISTRATION_RATELIMIT_RATE = '5/h'  # 5 регистраций в час с одного IP

# Настройки Django Honeypot
HONEYPOT_FIELD_NAME = 'email_confirm'  # Имя поля-ловушки
HONEYPOT_VALUE = ''  # Значение поля-ловушки (должно быть пустым)
HONEYPOT_VERIFIER = 'honeypot.decorators.verify_honeypot_value'
AXES_ENABLE_ADMIN = True
