# Generated by Django 5.2.4 on 2025-07-25 12:01

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_price_currency_alter_cartitem_price'),
    ]

    operations = [
        # Обновляем поле валюты для ограничения только рублем
        migrations.AlterField(
            model_name='cartitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(
                choices=[('RUB', 'Рубль')], 
                default='RUB', 
                max_length=3
            ),
        ),
    ]
