# Generated by Django 5.2.4 on 2025-07-25 16:57

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20250725_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('RUB', 'Рубль')], default='RUB', editable=False, max_length=3),
        ),
    ]
