# Generated by Django 5.2.4 on 2025-07-26 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cartitem_price_currency'),
        ('products', '0018_productsize_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID сессии')),
                ('quantity', models.PositiveIntegerField(verbose_name='Зарезервированное количество')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('expired', 'Истекло'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус резервирования')),
                ('expires_at', models.DateTimeField(verbose_name='Время истечения резервирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('preorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.preorder', verbose_name='Предзаказ')),
                ('preorder_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.preordersize', verbose_name='Размер предзаказа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
                ('product_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productsize', verbose_name='Размер товара')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Резервирование',
                'verbose_name_plural': 'Резервирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.reservation', verbose_name='Резервирование'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['expires_at', 'status'], name='cart_reserv_expires_cde7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='cart_reserv_user_id_b42e73_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['session_id', 'status'], name='cart_reserv_session_dc5352_idx'),
        ),
    ]
