# Generated by Django 5.2.4 on 2025-07-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_reservation_cartitem_reservation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='reservation',
        ),
    ]
