# Generated by Django 5.2.4 on 2025-07-26 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20250726_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.reservation', verbose_name='Резервирование'),
        ),
    ]
