# Generated by Django 5.2.4 on 2025-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=255, verbose_name='URL файла')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], default='image', max_length=20, verbose_name='Тип файла')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фоновое изображение/видео',
                'verbose_name_plural': 'Фоновые изображения/видео',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
