# Generated by Django 5.2.6 on 2025-09-06 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('operation_type', models.CharField(choices=[('backup_db', 'Резервное копирование БД'), ('backup_media', 'Резервное копирование медиа'), ('restore_db', 'Восстановление БД'), ('restore_media', 'Восстановление медиа')], default='backup_db', max_length=20, verbose_name='Тип операции')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], default='success', max_length=20, verbose_name='Статус')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог резервного копирования',
                'verbose_name_plural': 'Логи резервного копирования',
                'ordering': ['-timestamp'],
            },
        ),
    ]
